In [1]:
import pandas as pd
import numpy as np

Q1

In [2]:
pd.__version__

'3.0.5'

READ DATA

In [3]:
df=pd.read_csv('https://raw.githubusercontent.com/DataTalksClub/machine-learning-zoomcamp/main/cohorts/2026/data/car_fuel_efficiency_2026.csv')

In [4]:
df.head()

,model_year,origin,fuel_type,drivetrain,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
0,2006,Europe,Gasoline,Front-wheel drive,4,2180,6,243.0,3870,NaN,31.9
1,2008,Europe,Diesel,Front-wheel drive,4,2390,6,272.0,4210,NaN,31.3
2,1996,Asia,Gasoline,Front-wheel drive,5,2320,6,267.0,4240,17.3,27.5
3,1989,Europe,Gasoline,Front-wheel drive,4,2130,6,258.0,4490,18.7,28.5
4,1994,USA,Diesel,Front-wheel drive,3,2580,7,304.0,4510,17.5,31.0

Q2

In [5]:
len(df)

10000

Q3

In [6]:
df['fuel_type'].nunique()

3

Q4

In [7]:
df.isnull().sum()

model_year               0
origin                   0
fuel_type                0
drivetrain               0
num_doors                0
engine_displacement      0
num_cylinders            0
horsepower             877
vehicle_weight           0
acceleration           264
fuel_efficiency_mpg      0
dtype: int64

In [8]:
df.isnull().any().sum()

np.int64(2)

Q5

In [9]:
df.groupby('origin').fuel_efficiency_mpg.max()

origin
Asia      41.2
Europe    39.4
USA       38.2
Name: fuel_efficiency_mpg, dtype: float64

In [10]:
df.groupby('origin').fuel_efficiency_mpg.max().loc['Asia']

np.float64(41.2)

Q6

In [11]:
df.horsepower.median()

np.float64(254.0)

In [12]:
df.horsepower.value_counts().idxmax()

np.float64(252.0)

In [13]:
df['horsepower']=df.horsepower.fillna(df.horsepower.value_counts().idxmax())

In [14]:
df.horsepower.median()

np.float64(252.0)

Q7

In [15]:
df_asia=df[df['origin']=='Asia']

In [16]:
df_asia[["vehicle_weight","model_year"]]

      vehicle_weight  model_year
2               4240        1996
6               4310        1992
8               4230        1997
10              4420        1978
15              3950        2007
...              ...         ...
9984            4610        2011
9987            4530        2004
9990            3630        1975
9994            4610        1993
9996            4370        1993

[2994 rows x 2 columns]

In [17]:
df_asia[["vehicle_weight","model_year"]].head(7).values

array([[4240, 1996],
       [4310, 1992],
       [4230, 1997],
       [4420, 1978],
       [3950, 2007],
       [4750, 2021],
       [4450, 2019]])

In [18]:
X=df_asia[["vehicle_weight","model_year"]].head(7).values

In [19]:
XTX=X.T@X

In [20]:
XTX_inv = np.linalg.inv(XTX)

In [21]:
y = np.array([1100, 1300, 800, 900, 1000, 1100, 1200])

In [22]:
w = (XTX_inv @ X.T) @ y

In [23]:
sum(w)

np.float64(0.36919696904925486)